apiVersion: apps/v1
kind: Deployment
metadata:
  name: cini-mini-deployment
  labels:
    app: cini-mini
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cini-mini
  template:
    metadata:
      labels:
        app: cini-mini
    spec:
      containers:
      - name: cini-mini
        image: giridharaguptha/cini-mini-image:latest
        ports:
        - containerPort: 5000
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cini-mini-rollout
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cini-mini
  strategy:
    blueGreen:
      activeService: cini-mini-service
      previewService: cini-mini-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: cini-mini
    spec:
      containers:
      - name: cini-mini
        image: giridharaguptha/cini-mini-image-stable:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cini-mini-service
  namespace: devops
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: cini-mini
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cini-mini-preview-service
  namespace: devops
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: cini-mini
  type: NodePort