name: JFrog Artifact Deployment Trigger

on:
  repository_dispatch:
    types: [deployed]

jobs:
  handle_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Log Raw Payload
        run: |
          echo "Raw Payload: ${{ toJson(github.event) }}"

      - name: Extract and Process Relevant Fields
        run: |
          echo "Processing deployment event..."
          echo "Repository: ${{ github.event.client_payload.repositoryKey }}"
          echo "Artifact Path: ${{ github.event.client_payload.path }}"
          echo "Artifact Name: ${{ github.event.client_payload.name }}"
