name: JFrog Artifact Deployment Trigger

on:
  push:
    paths:
      - trigger-file.txt

jobs:
  handle_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Log Raw Payload
        run: |
          echo "Triggered !!!"
