name: Artifact Deployed Trigger

on:
  repository_dispatch:
    types: [deployed]

jobs:
  process_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Log Deployment Event
        run: |
          echo "Artifact deployed to JFrog repository!"
          echo "Repository: ${{ github.event.client_payload.repository }}"
          echo "Path: ${{ github.event.client_payload.artifact_path }}"
          echo "Artifact: ${{ github.event.client_payload.artifact_name }}"
